//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CallWidowsServiceSample.AdvantechWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdvantechWebServiceLocalSoap", Namespace="http://tempuri.org/")]
    public partial class AdvantechWebServiceLocal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCMS_CatalogName_ListByOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMS_CategoryName_ListByOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMS_Category_ListByOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSByBAAOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSByOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSByVer2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSByVer3OperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSTagListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMSDetailContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCMS_ProductCategoryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLogFromOn24OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRatingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBannerLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProductLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckeStoreProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBuyProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOnlineUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSEOAdminLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback getModelDownloadInStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRBUInfoByStoreIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckURLRedirectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdvantechWebServiceLocal() {
            this.Url = global::CallWidowsServiceSample.Properties.Settings.Default.CallWidowsServiceSample_AdvantechWebService_AdvantechWebServiceLocal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCMS_CatalogName_ListByCompletedEventHandler getCMS_CatalogName_ListByCompleted;
        
        /// <remarks/>
        public event getCMS_CategoryName_ListByCompletedEventHandler getCMS_CategoryName_ListByCompleted;
        
        /// <remarks/>
        public event getCMS_Category_ListByCompletedEventHandler getCMS_Category_ListByCompleted;
        
        /// <remarks/>
        public event getCMSByBAACompletedEventHandler getCMSByBAACompleted;
        
        /// <remarks/>
        public event getCMSByCompletedEventHandler getCMSByCompleted;
        
        /// <remarks/>
        public event getCMSByVer2CompletedEventHandler getCMSByVer2Completed;
        
        /// <remarks/>
        public event getCMSByVer3CompletedEventHandler getCMSByVer3Completed;
        
        /// <remarks/>
        public event getCMSTagListCompletedEventHandler getCMSTagListCompleted;
        
        /// <remarks/>
        public event getCMSMasterCompletedEventHandler getCMSMasterCompleted;
        
        /// <remarks/>
        public event getCMSDetailContentCompletedEventHandler getCMSDetailContentCompleted;
        
        /// <remarks/>
        public event getCMS_ProductCategoryListCompletedEventHandler getCMS_ProductCategoryListCompleted;
        
        /// <remarks/>
        public event GetLogFromOn24CompletedEventHandler GetLogFromOn24Completed;
        
        /// <remarks/>
        public event GetRatingCompletedEventHandler GetRatingCompleted;
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event AddBannerLogCompletedEventHandler AddBannerLogCompleted;
        
        /// <remarks/>
        public event AddProductLogCompletedEventHandler AddProductLogCompleted;
        
        /// <remarks/>
        public event CheckeStoreProductCompletedEventHandler CheckeStoreProductCompleted;
        
        /// <remarks/>
        public event CheckBuyProductCompletedEventHandler CheckBuyProductCompleted;
        
        /// <remarks/>
        public event getOnlineUserCompletedEventHandler getOnlineUserCompleted;
        
        /// <remarks/>
        public event getSEOAdminLinkCompletedEventHandler getSEOAdminLinkCompleted;
        
        /// <remarks/>
        public event getModelDownloadInStringCompletedEventHandler getModelDownloadInStringCompleted;
        
        /// <remarks/>
        public event getRBUInfoByStoreIDCompletedEventHandler getRBUInfoByStoreIDCompleted;
        
        /// <remarks/>
        public event CheckURLRedirectionCompletedEventHandler CheckURLRedirectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMS_CatalogName_ListBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getCMS_CatalogName_ListBy() {
            object[] results = this.Invoke("getCMS_CatalogName_ListBy", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getCMS_CatalogName_ListByAsync() {
            this.getCMS_CatalogName_ListByAsync(null);
        }
        
        /// <remarks/>
        public void getCMS_CatalogName_ListByAsync(object userState) {
            if ((this.getCMS_CatalogName_ListByOperationCompleted == null)) {
                this.getCMS_CatalogName_ListByOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMS_CatalogName_ListByOperationCompleted);
            }
            this.InvokeAsync("getCMS_CatalogName_ListBy", new object[0], this.getCMS_CatalogName_ListByOperationCompleted, userState);
        }
        
        private void OngetCMS_CatalogName_ListByOperationCompleted(object arg) {
            if ((this.getCMS_CatalogName_ListByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMS_CatalogName_ListByCompleted(this, new getCMS_CatalogName_ListByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMS_CategoryName_ListBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getCMS_CategoryName_ListBy(string strCatalogName) {
            object[] results = this.Invoke("getCMS_CategoryName_ListBy", new object[] {
                        strCatalogName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getCMS_CategoryName_ListByAsync(string strCatalogName) {
            this.getCMS_CategoryName_ListByAsync(strCatalogName, null);
        }
        
        /// <remarks/>
        public void getCMS_CategoryName_ListByAsync(string strCatalogName, object userState) {
            if ((this.getCMS_CategoryName_ListByOperationCompleted == null)) {
                this.getCMS_CategoryName_ListByOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMS_CategoryName_ListByOperationCompleted);
            }
            this.InvokeAsync("getCMS_CategoryName_ListBy", new object[] {
                        strCatalogName}, this.getCMS_CategoryName_ListByOperationCompleted, userState);
        }
        
        private void OngetCMS_CategoryName_ListByOperationCompleted(object arg) {
            if ((this.getCMS_CategoryName_ListByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMS_CategoryName_ListByCompleted(this, new getCMS_CategoryName_ListByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMS_Category_ListBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getCMS_Category_ListBy(string strCatalogName, string strFilter) {
            object[] results = this.Invoke("getCMS_Category_ListBy", new object[] {
                        strCatalogName,
                        strFilter});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getCMS_Category_ListByAsync(string strCatalogName, string strFilter) {
            this.getCMS_Category_ListByAsync(strCatalogName, strFilter, null);
        }
        
        /// <remarks/>
        public void getCMS_Category_ListByAsync(string strCatalogName, string strFilter, object userState) {
            if ((this.getCMS_Category_ListByOperationCompleted == null)) {
                this.getCMS_Category_ListByOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMS_Category_ListByOperationCompleted);
            }
            this.InvokeAsync("getCMS_Category_ListBy", new object[] {
                        strCatalogName,
                        strFilter}, this.getCMS_Category_ListByOperationCompleted, userState);
        }
        
        private void OngetCMS_Category_ListByOperationCompleted(object arg) {
            if ((this.getCMS_Category_ListByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMS_Category_ListByCompleted(this, new getCMS_Category_ListByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSByBAA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCMSByBAA(string stringBAAList, string stringCMSType, string stringRBU, int intReturnRow) {
            object[] results = this.Invoke("getCMSByBAA", new object[] {
                        stringBAAList,
                        stringCMSType,
                        stringRBU,
                        intReturnRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSByBAAAsync(string stringBAAList, string stringCMSType, string stringRBU, int intReturnRow) {
            this.getCMSByBAAAsync(stringBAAList, stringCMSType, stringRBU, intReturnRow, null);
        }
        
        /// <remarks/>
        public void getCMSByBAAAsync(string stringBAAList, string stringCMSType, string stringRBU, int intReturnRow, object userState) {
            if ((this.getCMSByBAAOperationCompleted == null)) {
                this.getCMSByBAAOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSByBAAOperationCompleted);
            }
            this.InvokeAsync("getCMSByBAA", new object[] {
                        stringBAAList,
                        stringCMSType,
                        stringRBU,
                        intReturnRow}, this.getCMSByBAAOperationCompleted, userState);
        }
        
        private void OngetCMSByBAAOperationCompleted(object arg) {
            if ((this.getCMSByBAACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSByBAACompleted(this, new getCMSByBAACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCMSBy(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_BAA, string[] list_eJF, string[] list_eL, string[] list_Activity, string strContactLocation, int intReturnRow) {
            object[] results = this.Invoke("getCMSBy", new object[] {
                        strCMSType,
                        strRBU,
                        list_CL,
                        list_BU,
                        list_PD,
                        list_BAA,
                        list_eJF,
                        list_eL,
                        list_Activity,
                        strContactLocation,
                        intReturnRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSByAsync(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_BAA, string[] list_eJF, string[] list_eL, string[] list_Activity, string strContactLocation, int intReturnRow) {
            this.getCMSByAsync(strCMSType, strRBU, list_CL, list_BU, list_PD, list_BAA, list_eJF, list_eL, list_Activity, strContactLocation, intReturnRow, null);
        }
        
        /// <remarks/>
        public void getCMSByAsync(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_BAA, string[] list_eJF, string[] list_eL, string[] list_Activity, string strContactLocation, int intReturnRow, object userState) {
            if ((this.getCMSByOperationCompleted == null)) {
                this.getCMSByOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSByOperationCompleted);
            }
            this.InvokeAsync("getCMSBy", new object[] {
                        strCMSType,
                        strRBU,
                        list_CL,
                        list_BU,
                        list_PD,
                        list_BAA,
                        list_eJF,
                        list_eL,
                        list_Activity,
                        strContactLocation,
                        intReturnRow}, this.getCMSByOperationCompleted, userState);
        }
        
        private void OngetCMSByOperationCompleted(object arg) {
            if ((this.getCMSByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSByCompleted(this, new getCMSByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSByVer2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCMSByVer2(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_BAA, string[] list_eJF, string[] list_eL, string[] list_Activity, string[] list_Tag, string strContactLocation, int intReturnRow) {
            object[] results = this.Invoke("getCMSByVer2", new object[] {
                        strCMSType,
                        strRBU,
                        list_CL,
                        list_BU,
                        list_PD,
                        list_BAA,
                        list_eJF,
                        list_eL,
                        list_Activity,
                        list_Tag,
                        strContactLocation,
                        intReturnRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSByVer2Async(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_BAA, string[] list_eJF, string[] list_eL, string[] list_Activity, string[] list_Tag, string strContactLocation, int intReturnRow) {
            this.getCMSByVer2Async(strCMSType, strRBU, list_CL, list_BU, list_PD, list_BAA, list_eJF, list_eL, list_Activity, list_Tag, strContactLocation, intReturnRow, null);
        }
        
        /// <remarks/>
        public void getCMSByVer2Async(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_BAA, string[] list_eJF, string[] list_eL, string[] list_Activity, string[] list_Tag, string strContactLocation, int intReturnRow, object userState) {
            if ((this.getCMSByVer2OperationCompleted == null)) {
                this.getCMSByVer2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSByVer2OperationCompleted);
            }
            this.InvokeAsync("getCMSByVer2", new object[] {
                        strCMSType,
                        strRBU,
                        list_CL,
                        list_BU,
                        list_PD,
                        list_BAA,
                        list_eJF,
                        list_eL,
                        list_Activity,
                        list_Tag,
                        strContactLocation,
                        intReturnRow}, this.getCMSByVer2OperationCompleted, userState);
        }
        
        private void OngetCMSByVer2OperationCompleted(object arg) {
            if ((this.getCMSByVer2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSByVer2Completed(this, new getCMSByVer2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSByVer3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCMSByVer3(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_Tag, string strContactLocation, int intReturnRow) {
            object[] results = this.Invoke("getCMSByVer3", new object[] {
                        strCMSType,
                        strRBU,
                        list_CL,
                        list_BU,
                        list_PD,
                        list_Tag,
                        strContactLocation,
                        intReturnRow});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSByVer3Async(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_Tag, string strContactLocation, int intReturnRow) {
            this.getCMSByVer3Async(strCMSType, strRBU, list_CL, list_BU, list_PD, list_Tag, strContactLocation, intReturnRow, null);
        }
        
        /// <remarks/>
        public void getCMSByVer3Async(string strCMSType, string strRBU, string[] list_CL, string[] list_BU, string[] list_PD, string[] list_Tag, string strContactLocation, int intReturnRow, object userState) {
            if ((this.getCMSByVer3OperationCompleted == null)) {
                this.getCMSByVer3OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSByVer3OperationCompleted);
            }
            this.InvokeAsync("getCMSByVer3", new object[] {
                        strCMSType,
                        strRBU,
                        list_CL,
                        list_BU,
                        list_PD,
                        list_Tag,
                        strContactLocation,
                        intReturnRow}, this.getCMSByVer3OperationCompleted, userState);
        }
        
        private void OngetCMSByVer3OperationCompleted(object arg) {
            if ((this.getCMSByVer3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSByVer3Completed(this, new getCMSByVer3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSTagList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCMSTagList(string cmsID) {
            object[] results = this.Invoke("getCMSTagList", new object[] {
                        cmsID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSTagListAsync(string cmsID) {
            this.getCMSTagListAsync(cmsID, null);
        }
        
        /// <remarks/>
        public void getCMSTagListAsync(string cmsID, object userState) {
            if ((this.getCMSTagListOperationCompleted == null)) {
                this.getCMSTagListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSTagListOperationCompleted);
            }
            this.InvokeAsync("getCMSTagList", new object[] {
                        cmsID}, this.getCMSTagListOperationCompleted, userState);
        }
        
        private void OngetCMSTagListOperationCompleted(object arg) {
            if ((this.getCMSTagListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSTagListCompleted(this, new getCMSTagListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCMSMaster(string cmsID) {
            object[] results = this.Invoke("getCMSMaster", new object[] {
                        cmsID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSMasterAsync(string cmsID) {
            this.getCMSMasterAsync(cmsID, null);
        }
        
        /// <remarks/>
        public void getCMSMasterAsync(string cmsID, object userState) {
            if ((this.getCMSMasterOperationCompleted == null)) {
                this.getCMSMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSMasterOperationCompleted);
            }
            this.InvokeAsync("getCMSMaster", new object[] {
                        cmsID}, this.getCMSMasterOperationCompleted, userState);
        }
        
        private void OngetCMSMasterOperationCompleted(object arg) {
            if ((this.getCMSMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSMasterCompleted(this, new getCMSMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMSDetailContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCMSDetailContent(string cmsID) {
            object[] results = this.Invoke("getCMSDetailContent", new object[] {
                        cmsID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCMSDetailContentAsync(string cmsID) {
            this.getCMSDetailContentAsync(cmsID, null);
        }
        
        /// <remarks/>
        public void getCMSDetailContentAsync(string cmsID, object userState) {
            if ((this.getCMSDetailContentOperationCompleted == null)) {
                this.getCMSDetailContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMSDetailContentOperationCompleted);
            }
            this.InvokeAsync("getCMSDetailContent", new object[] {
                        cmsID}, this.getCMSDetailContentOperationCompleted, userState);
        }
        
        private void OngetCMSDetailContentOperationCompleted(object arg) {
            if ((this.getCMSDetailContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMSDetailContentCompleted(this, new getCMSDetailContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCMS_ProductCategoryList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getCMS_ProductCategoryList(string CMSID) {
            object[] results = this.Invoke("getCMS_ProductCategoryList", new object[] {
                        CMSID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getCMS_ProductCategoryListAsync(string CMSID) {
            this.getCMS_ProductCategoryListAsync(CMSID, null);
        }
        
        /// <remarks/>
        public void getCMS_ProductCategoryListAsync(string CMSID, object userState) {
            if ((this.getCMS_ProductCategoryListOperationCompleted == null)) {
                this.getCMS_ProductCategoryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCMS_ProductCategoryListOperationCompleted);
            }
            this.InvokeAsync("getCMS_ProductCategoryList", new object[] {
                        CMSID}, this.getCMS_ProductCategoryListOperationCompleted, userState);
        }
        
        private void OngetCMS_ProductCategoryListOperationCompleted(object arg) {
            if ((this.getCMS_ProductCategoryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCMS_ProductCategoryListCompleted(this, new getCMS_ProductCategoryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLogFromOn24", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLogFromOn24(string strEvent, System.DateTime sDt, System.DateTime eDt, string strType) {
            object[] results = this.Invoke("GetLogFromOn24", new object[] {
                        strEvent,
                        sDt,
                        eDt,
                        strType});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogFromOn24Async(string strEvent, System.DateTime sDt, System.DateTime eDt, string strType) {
            this.GetLogFromOn24Async(strEvent, sDt, eDt, strType, null);
        }
        
        /// <remarks/>
        public void GetLogFromOn24Async(string strEvent, System.DateTime sDt, System.DateTime eDt, string strType, object userState) {
            if ((this.GetLogFromOn24OperationCompleted == null)) {
                this.GetLogFromOn24OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogFromOn24OperationCompleted);
            }
            this.InvokeAsync("GetLogFromOn24", new object[] {
                        strEvent,
                        sDt,
                        eDt,
                        strType}, this.GetLogFromOn24OperationCompleted, userState);
        }
        
        private void OnGetLogFromOn24OperationCompleted(object arg) {
            if ((this.GetLogFromOn24Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogFromOn24Completed(this, new GetLogFromOn24CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRating", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetRating(string url) {
            object[] results = this.Invoke("GetRating", new object[] {
                        url});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetRatingAsync(string url) {
            this.GetRatingAsync(url, null);
        }
        
        /// <remarks/>
        public void GetRatingAsync(string url, object userState) {
            if ((this.GetRatingOperationCompleted == null)) {
                this.GetRatingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRatingOperationCompleted);
            }
            this.InvokeAsync("GetRating", new object[] {
                        url}, this.GetRatingOperationCompleted, userState);
        }
        
        private void OnGetRatingOperationCompleted(object arg) {
            if ((this.GetRatingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRatingCompleted(this, new GetRatingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Add(int a, int b) {
            object[] results = this.Invoke("Add", new object[] {
                        a,
                        b});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(int a, int b) {
            this.AddAsync(a, b, null);
        }
        
        /// <remarks/>
        public void AddAsync(int a, int b, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        a,
                        b}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddBannerLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddBannerLog(int ID, string Type) {
            this.Invoke("AddBannerLog", new object[] {
                        ID,
                        Type});
        }
        
        /// <remarks/>
        public void AddBannerLogAsync(int ID, string Type) {
            this.AddBannerLogAsync(ID, Type, null);
        }
        
        /// <remarks/>
        public void AddBannerLogAsync(int ID, string Type, object userState) {
            if ((this.AddBannerLogOperationCompleted == null)) {
                this.AddBannerLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBannerLogOperationCompleted);
            }
            this.InvokeAsync("AddBannerLog", new object[] {
                        ID,
                        Type}, this.AddBannerLogOperationCompleted, userState);
        }
        
        private void OnAddBannerLogOperationCompleted(object arg) {
            if ((this.AddBannerLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBannerLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddProductLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddProductLog(string CATEGORY_ID, string PARENT_CATEGORY_ID, string BU, string Type) {
            this.Invoke("AddProductLog", new object[] {
                        CATEGORY_ID,
                        PARENT_CATEGORY_ID,
                        BU,
                        Type});
        }
        
        /// <remarks/>
        public void AddProductLogAsync(string CATEGORY_ID, string PARENT_CATEGORY_ID, string BU, string Type) {
            this.AddProductLogAsync(CATEGORY_ID, PARENT_CATEGORY_ID, BU, Type, null);
        }
        
        /// <remarks/>
        public void AddProductLogAsync(string CATEGORY_ID, string PARENT_CATEGORY_ID, string BU, string Type, object userState) {
            if ((this.AddProductLogOperationCompleted == null)) {
                this.AddProductLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProductLogOperationCompleted);
            }
            this.InvokeAsync("AddProductLog", new object[] {
                        CATEGORY_ID,
                        PARENT_CATEGORY_ID,
                        BU,
                        Type}, this.AddProductLogOperationCompleted, userState);
        }
        
        private void OnAddProductLogOperationCompleted(object arg) {
            if ((this.AddProductLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProductLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckeStoreProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckeStoreProduct(string PN, string CTOSsiteID, string ElementID) {
            object[] results = this.Invoke("CheckeStoreProduct", new object[] {
                        PN,
                        CTOSsiteID,
                        ElementID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckeStoreProductAsync(string PN, string CTOSsiteID, string ElementID) {
            this.CheckeStoreProductAsync(PN, CTOSsiteID, ElementID, null);
        }
        
        /// <remarks/>
        public void CheckeStoreProductAsync(string PN, string CTOSsiteID, string ElementID, object userState) {
            if ((this.CheckeStoreProductOperationCompleted == null)) {
                this.CheckeStoreProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckeStoreProductOperationCompleted);
            }
            this.InvokeAsync("CheckeStoreProduct", new object[] {
                        PN,
                        CTOSsiteID,
                        ElementID}, this.CheckeStoreProductOperationCompleted, userState);
        }
        
        private void OnCheckeStoreProductOperationCompleted(object arg) {
            if ((this.CheckeStoreProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckeStoreProductCompleted(this, new CheckeStoreProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckBuyProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckBuyProduct(string PN, string SiteID, string ElementID) {
            object[] results = this.Invoke("CheckBuyProduct", new object[] {
                        PN,
                        SiteID,
                        ElementID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBuyProductAsync(string PN, string SiteID, string ElementID) {
            this.CheckBuyProductAsync(PN, SiteID, ElementID, null);
        }
        
        /// <remarks/>
        public void CheckBuyProductAsync(string PN, string SiteID, string ElementID, object userState) {
            if ((this.CheckBuyProductOperationCompleted == null)) {
                this.CheckBuyProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBuyProductOperationCompleted);
            }
            this.InvokeAsync("CheckBuyProduct", new object[] {
                        PN,
                        SiteID,
                        ElementID}, this.CheckBuyProductOperationCompleted, userState);
        }
        
        private void OnCheckBuyProductOperationCompleted(object arg) {
            if ((this.CheckBuyProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBuyProductCompleted(this, new CheckBuyProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOnlineUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getOnlineUser() {
            object[] results = this.Invoke("getOnlineUser", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getOnlineUserAsync() {
            this.getOnlineUserAsync(null);
        }
        
        /// <remarks/>
        public void getOnlineUserAsync(object userState) {
            if ((this.getOnlineUserOperationCompleted == null)) {
                this.getOnlineUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOnlineUserOperationCompleted);
            }
            this.InvokeAsync("getOnlineUser", new object[0], this.getOnlineUserOperationCompleted, userState);
        }
        
        private void OngetOnlineUserOperationCompleted(object arg) {
            if ((this.getOnlineUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOnlineUserCompleted(this, new getOnlineUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSEOAdminLink", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSEOAdminLink(string Path) {
            object[] results = this.Invoke("getSEOAdminLink", new object[] {
                        Path});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSEOAdminLinkAsync(string Path) {
            this.getSEOAdminLinkAsync(Path, null);
        }
        
        /// <remarks/>
        public void getSEOAdminLinkAsync(string Path, object userState) {
            if ((this.getSEOAdminLinkOperationCompleted == null)) {
                this.getSEOAdminLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSEOAdminLinkOperationCompleted);
            }
            this.InvokeAsync("getSEOAdminLink", new object[] {
                        Path}, this.getSEOAdminLinkOperationCompleted, userState);
        }
        
        private void OngetSEOAdminLinkOperationCompleted(object arg) {
            if ((this.getSEOAdminLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSEOAdminLinkCompleted(this, new getSEOAdminLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getModelDownloadInString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getModelDownloadInString(string partNumber, string dataType) {
            object[] results = this.Invoke("getModelDownloadInString", new object[] {
                        partNumber,
                        dataType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getModelDownloadInStringAsync(string partNumber, string dataType) {
            this.getModelDownloadInStringAsync(partNumber, dataType, null);
        }
        
        /// <remarks/>
        public void getModelDownloadInStringAsync(string partNumber, string dataType, object userState) {
            if ((this.getModelDownloadInStringOperationCompleted == null)) {
                this.getModelDownloadInStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetModelDownloadInStringOperationCompleted);
            }
            this.InvokeAsync("getModelDownloadInString", new object[] {
                        partNumber,
                        dataType}, this.getModelDownloadInStringOperationCompleted, userState);
        }
        
        private void OngetModelDownloadInStringOperationCompleted(object arg) {
            if ((this.getModelDownloadInStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getModelDownloadInStringCompleted(this, new getModelDownloadInStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRBUInfoByStoreID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getRBUInfoByStoreID(string storeID) {
            object[] results = this.Invoke("getRBUInfoByStoreID", new object[] {
                        storeID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getRBUInfoByStoreIDAsync(string storeID) {
            this.getRBUInfoByStoreIDAsync(storeID, null);
        }
        
        /// <remarks/>
        public void getRBUInfoByStoreIDAsync(string storeID, object userState) {
            if ((this.getRBUInfoByStoreIDOperationCompleted == null)) {
                this.getRBUInfoByStoreIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRBUInfoByStoreIDOperationCompleted);
            }
            this.InvokeAsync("getRBUInfoByStoreID", new object[] {
                        storeID}, this.getRBUInfoByStoreIDOperationCompleted, userState);
        }
        
        private void OngetRBUInfoByStoreIDOperationCompleted(object arg) {
            if ((this.getRBUInfoByStoreIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRBUInfoByStoreIDCompleted(this, new getRBUInfoByStoreIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckURLRedirection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckURLRedirection() {
            object[] results = this.Invoke("CheckURLRedirection", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckURLRedirectionAsync() {
            this.CheckURLRedirectionAsync(null);
        }
        
        /// <remarks/>
        public void CheckURLRedirectionAsync(object userState) {
            if ((this.CheckURLRedirectionOperationCompleted == null)) {
                this.CheckURLRedirectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckURLRedirectionOperationCompleted);
            }
            this.InvokeAsync("CheckURLRedirection", new object[0], this.CheckURLRedirectionOperationCompleted, userState);
        }
        
        private void OnCheckURLRedirectionOperationCompleted(object arg) {
            if ((this.CheckURLRedirectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckURLRedirectionCompleted(this, new CheckURLRedirectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMS_CatalogName_ListByCompletedEventHandler(object sender, getCMS_CatalogName_ListByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMS_CatalogName_ListByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMS_CatalogName_ListByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMS_CategoryName_ListByCompletedEventHandler(object sender, getCMS_CategoryName_ListByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMS_CategoryName_ListByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMS_CategoryName_ListByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMS_Category_ListByCompletedEventHandler(object sender, getCMS_Category_ListByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMS_Category_ListByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMS_Category_ListByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSByBAACompletedEventHandler(object sender, getCMSByBAACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSByBAACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSByBAACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSByCompletedEventHandler(object sender, getCMSByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSByVer2CompletedEventHandler(object sender, getCMSByVer2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSByVer2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSByVer2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSByVer3CompletedEventHandler(object sender, getCMSByVer3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSByVer3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSByVer3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSTagListCompletedEventHandler(object sender, getCMSTagListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSTagListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSTagListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSMasterCompletedEventHandler(object sender, getCMSMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMSDetailContentCompletedEventHandler(object sender, getCMSDetailContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMSDetailContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMSDetailContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getCMS_ProductCategoryListCompletedEventHandler(object sender, getCMS_ProductCategoryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCMS_ProductCategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCMS_ProductCategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetLogFromOn24CompletedEventHandler(object sender, GetLogFromOn24CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogFromOn24CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogFromOn24CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetRatingCompletedEventHandler(object sender, GetRatingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRatingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRatingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AddBannerLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AddProductLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckeStoreProductCompletedEventHandler(object sender, CheckeStoreProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckeStoreProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckeStoreProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckBuyProductCompletedEventHandler(object sender, CheckBuyProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBuyProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBuyProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getOnlineUserCompletedEventHandler(object sender, getOnlineUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOnlineUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOnlineUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getSEOAdminLinkCompletedEventHandler(object sender, getSEOAdminLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSEOAdminLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSEOAdminLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getModelDownloadInStringCompletedEventHandler(object sender, getModelDownloadInStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getModelDownloadInStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getModelDownloadInStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getRBUInfoByStoreIDCompletedEventHandler(object sender, getRBUInfoByStoreIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRBUInfoByStoreIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRBUInfoByStoreIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckURLRedirectionCompletedEventHandler(object sender, CheckURLRedirectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckURLRedirectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckURLRedirectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591